## David's Diabetes Data - A 2025 Deep Dive WIP

My boyfriend, David, has type 1 diabetes. He tracks his blood sugar levels with a standard glucometer and a Freestyle Libre 2 arm sensor, which should ideally be within the range of 5-7mmol. His finger prick testing, insulin injections at meal times and correction doses (of sugar or insulin) are recorded in the MySugr app alongside additional information (time of day, date and information tags). The following data set records approximately 4 years of data in 15,000 rows of data.

The **goal of this analysis** is to highlight the factors influencing low and high glucose events - some within this data set i.e. time of day, weekday vs weekend, activity and link it to external data e.g. daily weather, win or lose at daily Wordle puzzle.

# Read in data and examine it

**Step 1: Read in the .csv file**

In [ ]:
# Load libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
# Create dataframe called df that loads the data from the specified path
df = pd.read_csv('mySugrJuly25.csv')
# Check top rows of data
df.head(30)

,Date,Time,Tags,Blood Sugar Measurement (mmol/L),Insulin Injection Units (Pen),Basal Injection Units,Insulin Injection Units (pump),Insulin (Meal),Insulin (Correction),Temporary Basal Percentage,...,Location,Blood pressure,Body weight (kg),HbA1c (mmol/mol),Ketones,Food type,Medication,Timezone,Latitude,Longitude
0,24 Jul 2025,13:21:14,"Lunch,Before meal",4.6,NaN,NaN,NaN,3.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GMT+01:00,NaN,NaN
1,24 Jul 2025,13:18:46,"Before meal,Breakfast",5.7,NaN,NaN,NaN,2.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GMT+01:00,NaN,NaN
2,23 Jul 2025,20:07:44,"Before meal,Dinner",7.6,NaN,NaN,NaN,3.0,0.5,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GMT+01:00,NaN,NaN
3,23 Jul 2025,16:45:09,"Office work,Snack,After meal",4.6,NaN,NaN,NaN,1.5,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GMT+01:00,NaN,NaN
4,23 Jul 2025,16:32:35,"Office work,After meal",4.5,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GMT+01:00,NaN,NaN
5,23 Jul 2025,13:17:25,"Lunch,Before meal",6.2,NaN,NaN,NaN,2.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GMT+01:00,NaN,NaN
6,23 Jul 2025,10:02:16,"Before meal,Breakfast",4.8,NaN,NaN,NaN,2.5,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GMT+01:00,NaN,NaN
7,23 Jul 2025,9:34:00,NaN,5.4,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GMT+01:00,NaN,NaN
8,22 Jul 2025,22:31:30,NaN,NaN,NaN,10.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GMT+01:00,NaN,NaN
9,22 Jul 2025,19:52:55,"Before meal,Dinner",4.6,NaN,NaN,NaN,6.5,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GMT+01:00,NaN,NaN
10,22 Jul 2025,13:24:29,"Lunch,Before meal",4.5,NaN,NaN,NaN,1.5,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GMT+01:00,NaN,NaN
11,22 Jul 2025,9:54:05,"Before meal,Breakfast",8.3,NaN,NaN,NaN,3.0,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GMT+01:00,NaN,NaN
12,21 Jul 2025,22:31:05,NaN,NaN,NaN,10.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GMT+01:00,NaN,NaN
13,21 Jul 2025,20:02:21,"Before meal,Dinner",5.5,NaN,NaN,NaN,4.5,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GMT+01:00,NaN,NaN
14,21 Jul 2025,16:27:07,"Stress,Office work,After meal",6.3,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GMT+01:00,NaN,NaN
15,21 Jul 2025,13:45:00,"Lunch,Before meal",7.7,NaN,NaN,NaN,3.0,0.5,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GMT+01:00,NaN,NaN
16,21 Jul 2025,9:50:54,"Before meal,Breakfast",6.2,NaN,NaN,NaN,3.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GMT+01:00,NaN,NaN
17,20 Jul 2025,23:37:46,NaN,NaN,NaN,10.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GMT+01:00,NaN,NaN
18,20 Jul 2025,18:39:12,"Before meal,Dinner",9.0,NaN,NaN,NaN,4.0,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GMT+01:00,NaN,NaN
19,20 Jul 2025,14:31:49,"Lunch,Before meal",6.0,NaN,NaN,NaN,2.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GMT+01:00,NaN,NaN
20,20 Jul 2025,11:43:47,"Hyperglycemia feeling,After meal",9.2,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GMT+01:00,NaN,NaN
21,20 Jul 2025,10:25:00,After meal,5.6,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GMT+01:00,NaN,NaN
22,20 Jul 2025,9:46:39,"Before meal,Breakfast",3.9,NaN,NaN,NaN,2.5,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GMT+01:00,NaN,NaN
23,19 Jul 2025,23:54:10,NaN,4.1,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GMT+01:00,NaN,NaN
24,19 Jul 2025,22:53:05,NaN,5.2,NaN,10.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GMT+01:00,NaN,NaN
25,19 Jul 2025,15:13:06,After meal,5.6,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GMT+01:00,NaN,NaN
26,19 Jul 2025,15:03:04,"Snack,After meal",4.4,NaN,NaN,NaN,0.5,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GMT+01:00,NaN,NaN
27,19 Jul 2025,14:42:40,"Lunch,Before meal",4.6,NaN,NaN,NaN,2.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GMT+01:00,NaN,NaN
28,19 Jul 2025,12:03:59,"Snack,After meal",5.6,NaN,NaN,NaN,1.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GMT+01:00,NaN,NaN
29,19 Jul 2025,11:53:06,NaN,3.1,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GMT+01:00,NaN,NaN

# **Step 2: Examine data**
- Here I am getting a sense of the amount of usable data, evaluating if the data columns have been parsed as the correct data type and seeing if any columns should be alterned or dropped due to missing data.

In [ ]:
# Check out the data structure and types
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15643 entries, 0 to 15642
Data columns (total 28 columns):
 #   Column                                                   Non-Null Count  Dtype
---  ------                                                   --------------  -----
 0   Date                                                     15643 non-null  object
 1   Time                                                     15643 non-null  object
 2   Tags                                                     11446 non-null  object
 3   Blood Sugar Measurement (mmol/L)                         12197 non-null  float64
 4   Insulin Injection Units (Pen)                            0 non-null      float64
 5   Basal Injection Units                                    1137 non-null   float64
 6   Insulin Injection Units (pump)                           0 non-null      float64
 7   Insulin (Meal)                                           4016 non-null   float64
 8   Insulin (Correction)                                     772 non-null    float64
 9   Temporary Basal Percentage                               0 non-null      float64
 10  Temporary Basal Duration (Minutes)                       0 non-null      float64
 11  Meal Carbohydrates (Grams, Factor 1)                     5847 non-null   float64
 12  Meal Descriptions                                        5 non-null      object
 13  Activity Duration (Minutes)                              13 non-null     float64
 14  Activity Intensity (1: Cosy, 2: Ordinary, 3: Demanding)  0 non-null      float64
 15  Activity Description                                     12 non-null     object
 16  Steps                                                    0 non-null      float64
 17  Note                                                     479 non-null    object
 18  Location                                                 0 non-null      float64
 19  Blood pressure                                           0 non-null      float64
 20  Body weight (kg)                                         0 non-null      float64
 21  HbA1c (mmol/mol)                                         0 non-null      float64
 22  Ketones                                                  55 non-null     float64
 23  Food type                                                0 non-null      float64
 24  Medication                                               0 non-null      float64
 25  Timezone                                                 15643 non-null  object
 26  Latitude                                                 0 non-null      float64
 27  Longitude                                                0 non-null      float64
dtypes: float64(21), object(7)
memory usage: 3.3+ MB

In [ ]:
# Get a full view of the top 100 rows, which is the most recent data
# Check for rows that display differently from the majority e.g. row 8

from IPython.display import display
with pd.option_context('display.max_rows', 100, 'display.max_columns', 28):
    display(df.head(100))

,Date,Time,Tags,Blood Sugar Measurement (mmol/L),Insulin Injection Units (Pen),Basal Injection Units,Insulin Injection Units (pump),Insulin (Meal),Insulin (Correction),Temporary Basal Percentage,Temporary Basal Duration (Minutes),"Meal Carbohydrates (Grams, Factor 1)",Meal Descriptions,Activity Duration (Minutes),"Activity Intensity (1: Cosy, 2: Ordinary, 3: Demanding)",Activity Description,Steps,Note,Location,Blood pressure,Body weight (kg),HbA1c (mmol/mol),Ketones,Food type,Medication,Timezone,Latitude,Longitude
0,24 Jul 2025,13:21:14,"Lunch,Before meal",4.6,NaN,NaN,NaN,3.0,NaN,NaN,NaN,54.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GMT+01:00,NaN,NaN
1,24 Jul 2025,13:18:46,"Before meal,Breakfast",5.7,NaN,NaN,NaN,2.0,NaN,NaN,NaN,22.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GMT+01:00,NaN,NaN
2,23 Jul 2025,20:07:44,"Before meal,Dinner",7.6,NaN,NaN,NaN,3.0,0.5,NaN,NaN,54.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GMT+01:00,NaN,NaN
3,23 Jul 2025,16:45:09,"Office work,Snack,After meal",4.6,NaN,NaN,NaN,1.5,NaN,NaN,NaN,28.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GMT+01:00,NaN,NaN
4,23 Jul 2025,16:32:35,"Office work,After meal",4.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GMT+01:00,NaN,NaN
5,23 Jul 2025,13:17:25,"Lunch,Before meal",6.2,NaN,NaN,NaN,2.0,NaN,NaN,NaN,33.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GMT+01:00,NaN,NaN
6,23 Jul 2025,10:02:16,"Before meal,Breakfast",4.8,NaN,NaN,NaN,2.5,NaN,NaN,NaN,34.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GMT+01:00,NaN,NaN
7,23 Jul 2025,9:34:00,NaN,5.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GMT+01:00,NaN,NaN
8,22 Jul 2025,22:31:30,NaN,NaN,NaN,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GMT+01:00,NaN,NaN
9,22 Jul 2025,19:52:55,"Before meal,Dinner",4.6,NaN,NaN,NaN,6.5,NaN,NaN,NaN,113.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GMT+01:00,NaN,NaN
10,22 Jul 2025,13:24:29,"Lunch,Before meal",4.5,NaN,NaN,NaN,1.5,NaN,NaN,NaN,33.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GMT+01:00,NaN,NaN
11,22 Jul 2025,9:54:05,"Before meal,Breakfast",8.3,NaN,NaN,NaN,3.0,1.0,NaN,NaN,36.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GMT+01:00,NaN,NaN
12,21 Jul 2025,22:31:05,NaN,NaN,NaN,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GMT+01:00,NaN,NaN
13,21 Jul 2025,20:02:21,"Before meal,Dinner",5.5,NaN,NaN,NaN,4.5,NaN,NaN,NaN,70.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GMT+01:00,NaN,NaN
14,21 Jul 2025,16:27:07,"Stress,Office work,After meal",6.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GMT+01:00,NaN,NaN
15,21 Jul 2025,13:45:00,"Lunch,Before meal",7.7,NaN,NaN,NaN,3.0,0.5,NaN,NaN,47.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GMT+01:00,NaN,NaN
16,21 Jul 2025,9:50:54,"Before meal,Breakfast",6.2,NaN,NaN,NaN,3.0,NaN,NaN,NaN,33.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GMT+01:00,NaN,NaN
17,20 Jul 2025,23:37:46,NaN,NaN,NaN,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GMT+01:00,NaN,NaN
18,20 Jul 2025,18:39:12,"Before meal,Dinner",9.0,NaN,NaN,NaN,4.0,1.0,NaN,NaN,59.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GMT+01:00,NaN,NaN
19,20 Jul 2025,14:31:49,"Lunch,Before meal",6.0,NaN,NaN,NaN,2.0,NaN,NaN,NaN,31.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GMT+01:00,NaN,NaN
20,20 Jul 2025,11:43:47,"Hyperglycemia feeling,After meal",9.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GMT+01:00,NaN,NaN
21,20 Jul 2025,10:25:00,After meal,5.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GMT+01:00,NaN,NaN
22,20 Jul 2025,9:46:39,"Before meal,Breakfast",3.9,NaN,NaN,NaN,2.5,NaN,NaN,NaN,35.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GMT+01:00,NaN,NaN
23,19 Jul 2025,23:54:10,NaN,4.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GMT+01:00,NaN,NaN
24,19 Jul 2025,22:53:05,NaN,5.2,NaN,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GMT+01:00,NaN,NaN
25,19 Jul 2025,15:13:06,After meal,5.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GMT+01:00,NaN,NaN
26,19 Jul 2025,15:03:04,"Snack,After meal",4.4,NaN,NaN,NaN,0.5,NaN,NaN,NaN,15.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GMT+01:00,NaN,NaN
27,19 Jul 2025,14:42:40,"Lunch,Before meal",4.6,NaN,NaN,NaN,2.0,NaN,NaN,NaN,39.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GMT+01:00,NaN,NaN
28,19 Jul 2025,12:03:59,"Snack,After meal",5.6,NaN,NaN,NaN,1.0,NaN,NaN,NaN,15.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GMT+01:00,NaN,NaN
29,19 Jul 2025,11:53:06,NaN,3.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GMT+01:00,NaN,NaN
30,19 Jul 2025,10:44:46,"Before meal,Breakfast",6.2,NaN,NaN,NaN,2.0,NaN,NaN,NaN,20.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GMT+01:00,NaN,NaN
31,19 Jul 2025,0:33:59,"Snack,After meal",4.7,NaN,NaN,NaN,0.5,NaN,NaN,NaN,14.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GMT+01:00,NaN,NaN
32,19 Jul 2025,0:16:53,"Snack,After meal",5.4,NaN,NaN,NaN,2.5,NaN,NaN,NaN,42.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GMT+01:00,NaN,NaN
33,18 Jul 2025,23:37:53,NaN,5.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GMT+01:00,NaN,NaN
34,18 Jul 2025,21:06:16,"Hyperglycemia feeling,After meal",9.7,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GMT+01:00,NaN,NaN
35,18 Jul 2025,17:01:13,"Before meal,Dinner",4.4,NaN,NaN,NaN,1.0,NaN,NaN,NaN,20.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GMT+01:00,NaN,NaN
36,18 Jul 2025,16:38:13,"Snack,After meal",4.3,NaN,NaN,NaN,0.5,NaN,NaN,NaN,12.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GMT+01:00,NaN,NaN
37,18 Jul 2025,13:43:19,"Lunch,Before meal",5.8,NaN,NaN,NaN,2.5,NaN,NaN,NaN,35.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GMT+01:00,NaN,NaN
38,18 Jul 2025,9:24:04,NaN,5.3,NaN,NaN,NaN,1.5,NaN,NaN,NaN,19.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GMT+01:00,NaN,NaN
39,18 Jul 2025,1:02:23,Bedtime,3.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GMT+01:00,NaN,NaN
40,17 Jul 2025,22:31:13,NaN,NaN,NaN,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GMT+01:00,NaN,NaN
41,17 Jul 2025,19:42:40,"Snack,After meal",5.7,NaN,NaN,NaN,2.0,NaN,NaN,NaN,28.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GMT+01:00,NaN,NaN
42,17 Jul 2025,17:21:55,"Before meal,Dinner",5.2,NaN,NaN,NaN,3.5,NaN,NaN,NaN,61.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GMT+01:00,NaN,NaN
43,17 Jul 2025,16:34:06,"Hypoglycemia feeling,After meal",5.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GMT+01:00,NaN,NaN
44,17 Jul 2025,16:18:08,Hypoglycemia feeling,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GMT+01:00,NaN,NaN
45,17 Jul 2025,13:23:27,"Lunch,Before meal,Carb guess",8.8,NaN,NaN,NaN,2.0,1.0,NaN,NaN,34.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GMT+01:00,NaN,NaN
46,17 Jul 2025,12:45:56,After meal,4.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GMT+01:00,NaN,NaN
47,17 Jul 2025,11:54:01,After meal,4.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GMT+01:00,NaN,NaN
48,17 Jul 2025,9:07:40,"Before meal,Breakfast",4.3,NaN,NaN,NaN,2.5,NaN,NaN,NaN,34.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GMT+01:00,NaN,NaN
49,16 Jul 2025,21:15:31,After meal,12.4,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GMT+01:00,NaN,NaN
50,16 Jul 2025,17:45:26,"Before meal,Dinner",8.3,NaN,NaN,NaN,4.0,1.0,NaN,NaN,68.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GMT+01:00,NaN,NaN
51,16 Jul 2025,14:16:56,After meal,5.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GMT+01:00,NaN,NaN
52,16 Jul 2025,14:01:30,"Hyperglycemia feeling,After meal",2.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GMT+01:00,NaN,NaN
53,16 Jul 2025,13:38:53,After meal,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GMT+01:00,NaN,NaN
54,16 Jul 2025,12:35:30,"Lunch,Eating out,Before meal,Carb guess",5.0,NaN,NaN,NaN,1.5,NaN,NaN,NaN,30.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GMT+01:00,NaN,NaN
55,16 Jul 2025,8:54:48,"Before meal,Breakfast",5.6,NaN,NaN,NaN,3.0,NaN,NaN,NaN,34.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GMT+01:00,NaN,NaN
56,15 Jul 2025,23:37:20,"After meal,Bedtime",7.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GMT+01:00,NaN,NaN
57,15 Jul 2025,22:29:31,NaN,NaN,NaN,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GMT+01:00,NaN,NaN
58,15 Jul 2025,20:04:31,"Snack,After meal",6.8,NaN,NaN,NaN,2.0,NaN,NaN,NaN,28.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GMT+01:00,NaN,NaN
59,15 Jul 2025,19:02:18,"Hypoglycemia feeling,After meal",3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GMT+01:00,NaN,NaN
60,15 Jul 2025,17:53:10,"Before meal,Dinner",5.2,NaN,NaN,NaN,4.0,NaN,NaN,NaN,69.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GMT+01:00,NaN,NaN
61,15 Jul 2025,13:23:08,"Lunch,Before meal",4.6,NaN,NaN,NaN,2.5,NaN,NaN,NaN,48.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GMT+01:00,NaN,NaN
62,15 Jul 2025,8:54:07,"Before meal,Breakfast",5.1,NaN,NaN,NaN,3.0,NaN,NaN,NaN,34.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GMT+01:00,NaN,NaN
63,14 Jul 2025,22:57:46,"Snack,After meal",7.0,NaN,NaN,NaN,1.0,NaN,NaN,NaN,15.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GMT+01:00,NaN,NaN
64,14 Jul 2025,22:34:56,NaN,NaN,NaN,23.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GMT+01:00,NaN,NaN
65,14 Jul 2025,22:17:56,NaN,7.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GMT+01:00,NaN,NaN
66,14 Jul 2025,19:42:47,"Snack,After meal",5.5,NaN,NaN,NaN,1.5,NaN,NaN,NaN,28.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GMT+01:00,NaN,NaN
67,14 Jul 2025,18:40:30,After meal,3.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GMT+01:00,NaN,NaN
68,14 Jul 2025,17:00:43,"Before meal,Carb guess,Dinner",5.0,NaN,NaN,NaN,5.0,NaN,NaN,NaN,85.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GMT+01:00,NaN,NaN
69,14 Jul 2025,13:36:05,"Snack,After meal",7.5,NaN,NaN,NaN,1.5,NaN,NaN,NaN,22.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GMT+01:00,NaN,NaN
70,14 Jul 2025,13:20:29,"Lunch,Before meal",8.7,NaN,NaN,NaN,2.5,0.5,NaN,NaN,36.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GMT+01:00,NaN,NaN
71,14 Jul 2025,12:41:40,After meal,3.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GMT+01:00,NaN,NaN
72,14 Jul 2025,10:56:37,After meal,6.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GMT+01:00,NaN,NaN
73,14 Jul 2025,8:33:09,"Before meal,Breakfast",4.3,NaN,NaN,NaN,3.0,NaN,NaN,NaN,37.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GMT+01:00,NaN,NaN
74,14 Jul 2025,7:27:21,Foot on the floor,3.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GMT+01:00,NaN,NaN
75,13 Jul 2025,23:26:11,"After meal,Bedtime",7.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GMT+01:00,NaN,NaN
76,13 Jul 2025,18:55:29,NaN,5.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GMT+01:00,NaN,NaN
77,13 Jul 2025,18:43:10,"Hypoglycemia feeling,After meal",3.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GMT+01:00,NaN,NaN
78,13 Jul 2025,17:05:21,"Before meal,Dinner",8.7,NaN,NaN,NaN,4.0,0.5,NaN,NaN,69.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GMT+01:00,NaN,NaN
79,13 Jul 2025,14:36:03,"Snack,After meal",6.5,NaN,NaN,NaN,0.5,NaN,NaN,NaN,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GMT+01:00,NaN,NaN
80,13 Jul 2025,12:35:51,"Hypoglycemia feeling,Lunch,Eating out,Tired,Be...",6.7,NaN,NaN,NaN,4.0,NaN,NaN,NaN,60.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GMT+01:00,NaN,NaN
81,13 Jul 2025,9:30:44,"Before meal,Breakfast",7.2,NaN,NaN,NaN,4.0,0.5,NaN,NaN,43.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GMT+01:00,NaN,NaN
82,12 Jul 2025,21:58:02,"Snack,After meal",6.2,NaN,10.0,NaN,0.5,NaN,NaN,NaN,11.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GMT+01:00,NaN,NaN
83,12 Jul 2025,19:46:49,"After meal,Bedtime",4.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GMT+01:00,NaN,NaN
84,12 Jul 2025,18:40:30,"Snack,After meal",6.1,NaN,NaN,NaN,1.5,NaN,NaN,NaN,23.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GMT+01:00,NaN,NaN
85,12 Jul 2025,18:31:02,"Hypoglycemia feeling,After meal,Dinner",3.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GMT+01:00,NaN,NaN
86,12 Jul 2025,18:19:53,"Hypoglycemia feeling,After meal",3.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GMT+01:00,NaN,NaN
87,12 Jul 2025,17:30:20,"Before meal,Carb guess,Dinner",6.8,NaN,NaN,NaN,4.5,0.5,NaN,NaN,70.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GMT+01:00,NaN,NaN
88,12 Jul 2025,15:39:53,After meal,8.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GMT+01:00,NaN,NaN
89,12 Jul 2025,13:17:08,"Lunch,Before meal",4.4,NaN,NaN,NaN,2.5,NaN,NaN,NaN,48.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GMT+01:00,NaN,NaN
90,12 Jul 2025,9:43:39,"Before meal,Breakfast",5.3,NaN,NaN,NaN,2.0,NaN,NaN,NaN,22.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GMT+01:00,NaN,NaN
91,11 Jul 2025,22:43:16,"After meal,Bedtime",6.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GMT+01:00,NaN,NaN
92,11 Jul 2025,22:30:05,NaN,NaN,NaN,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GMT+01:00,NaN,NaN
93,11 Jul 2025,20:56:20,"Snack,After meal",7.2,NaN,NaN,NaN,1.0,NaN,NaN,NaN,12.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GMT+01:00,NaN,NaN
94,11 Jul 2025,18:32:43,"Before meal,Dinner",5.9,NaN,NaN,NaN,4.5,NaN,NaN,NaN,72.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GMT+01:00,NaN,NaN
95,11 Jul 2025,15:04:40,"Hypoglycemia feeling,Snack,Before meal,After meal",4.2,NaN,NaN,NaN,1.0,NaN,NaN,NaN,22.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GMT+01:00,NaN,NaN
96,11 Jul 2025,12:38:04,"Lunch,Before meal",7.8,NaN,NaN,NaN,2.0,NaN,NaN,NaN,33.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GMT+01:00,NaN,NaN
97,11 Jul 2025,11:35:09,"Driving,Hypoglycemia feeling,On the way,After ...",9.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GMT+01:00,NaN,NaN
98,11 Jul 2025,9:48:59,"Before meal,Breakfast",8.4,NaN,NaN,NaN,3.5,1.0,NaN,NaN,42.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GMT+01:00,NaN,NaN
99,10 Jul 2025,22:14:32,NaN,NaN,NaN,12.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GMT+01:00,NaN,NaN

In [ ]:
# Check for valid data in the Ketones column (this is an important data point as dangerous ketones are produced when blood sugar levels are too high (hyperglycemia))
# Created a new subset of data in a dataframe using the .loc method to find rows with non-null ketone data (.notnull method)
ketones_df = df.loc[df['Ketones'].notnull()]
print(ketones_df)

              Date      Time  \
187     2 Jul 2025  12:13:22
422     7 Jun 2025  11:27:27
544    26 May 2025  11:13:11
757     8 May 2025  11:19:57
760     8 May 2025   9:16:34
829     1 May 2025  11:51:16
1332   20 Mar 2025  12:29:32
1434   12 Mar 2025  17:24:00
1522    2 Mar 2025  20:22:39
1808    2 Feb 2025  10:19:57
1816    1 Feb 2025  11:59:25
1843   29 Jan 2025  16:54:15
1951   16 Jan 2025  15:39:26
2407   29 Nov 2024  16:10:57
2413   29 Nov 2024  10:56:05
2707    7 Nov 2024   9:19:23
2768   31 Oct 2024  20:16:03
2823   26 Oct 2024  13:52:06
2837   24 Oct 2024  22:42:46
2839   24 Oct 2024  21:48:46
2873   20 Oct 2024  11:34:52
3061    2 Oct 2024  10:30:56
3083    1 Oct 2024   9:11:42
3600    1 Aug 2024  12:57:35
4269   26 May 2024   8:40:42
4676    3 May 2024   9:13:00
4751   29 Apr 2024   9:06:16
5010   13 Apr 2024   9:30:33
5186    3 Apr 2024   9:27:13
5206    2 Apr 2024  10:35:09
5587    8 Mar 2024   9:30:00
6456   13 Jan 2024  11:40:01
6460   13 Jan 2024  10:05:58
6776   24 Dec 2023  16:33:07
6959   12 Dec 2023   9:22:04
7297   20 Nov 2023  11:29:00
7351   17 Nov 2023   8:49:00
8481   1 Sept 2023  12:12:00
8483   1 Sept 2023  10:53:00
8484   1 Sept 2023  10:30:00
8564   27 Aug 2023  12:14:13
9004   26 Jul 2023  12:21:00
9006   26 Jul 2023  11:36:00
9394   27 Jun 2023  11:17:00
9569   16 Jun 2023  12:13:00
10644   3 Apr 2023  13:20:46
10648   3 Apr 2023   9:09:00
10652   2 Apr 2023  16:20:00
11476  23 Jan 2023  11:06:00
11528  19 Jan 2023  11:52:00
11662   9 Jan 2023  20:19:36
11782   1 Jan 2023  16:30:00
12255  30 Nov 2022  11:51:00
12265  29 Nov 2022  17:08:00
12267  29 Nov 2022  16:33:00

                                                    Tags  \
187                                     Tired,After meal
422                                                  NaN
544                     Hyperglycemia feeling,After meal
757                                                  NaN
760                                Before meal,Breakfast
829                                                  NaN
1332                                                Sick
1434                                                 NaN
1522                                          After meal
1808                               Before meal,Breakfast
1816              Hyperglycemia feeling,Tired,After meal
1843                                                 NaN
1951                                                 NaN
2407                              Office work,After meal
2413                                                 NaN
2707                               Before meal,Breakfast
2768   Hyperglycemia feeling,Special situation,After ...
2823                                                 NaN
2837                    Hyperglycemia feeling,After meal
2839                                          After meal
2873                                                 NaN
3061                        Office work,Tired,After meal
3083                               Before meal,Breakfast
3600                                                 NaN
4269                                                 NaN
4676                                 Before meal,Fasting
4751                                                 NaN
5010                                 Before meal,Fasting
5186                                                 NaN
5206                                                 NaN
5587                                 Before meal,Fasting
6456                                                 NaN
6460                                                 NaN
6776                                                 NaN
6959                                                 NaN
7297                         Office work,After meal,Sick
7351                            Before meal,Fasting,Sick
8481                              Office work,After meal
8483                              Office work,After meal
8484        Hyperglycemia feeling,Office work,After meal
8564                                                 NaN
9004                              Office work,After meal
9006        Hyperglycemia feeling,Office work,After meal
9394        Hyperglycemia feeling,Office work,After meal
9569        Hyperglycemia feeling,Office work,After meal
10644                                                NaN
10648          Hyperglycemia feeling,Before meal,Fasting
10652                                         After meal
11476       Hyperglycemia feeling,Stress,Angry,Sad,Tired
11528       Hyperglycemia feeling,Office work,After meal
11662                                                NaN
11782                                                NaN
12255  Hyperglycemia feeling,Office work,After meal,Sick
12265                                   Office work,Sick
12267                                   Office work,Sick

       Blood Sugar Measurement (mmol/L)  Insulin Injection Units (Pen)  \
187                                12.6                            NaN
422                                 NaN                            NaN
544                                13.4                            NaN
757                                16.3                            NaN
760                                15.9                            NaN
829                                 NaN                            NaN
1332                                4.5                            NaN
1434                                NaN                            NaN
1522                               14.7                            NaN
1808                               13.5                            NaN
1816                               14.5                            NaN
1843                                NaN                            NaN
1951                                NaN                            NaN
2407                               13.2                            NaN
2413                                NaN                            NaN
2707                               13.3                            NaN
2768                               15.5                            NaN
2823                               14.7                            NaN
2837                               17.7                            NaN
2839                               16.1                            NaN
2873                                NaN                            NaN
3061                               13.1                            NaN
3083                               15.0                            NaN
3600                                NaN                            NaN
4269                                NaN                            NaN
4676                               13.5                            NaN
4751                                NaN                            NaN
5010                               12.7                            NaN
5186                                NaN                            NaN
5206                                NaN                            NaN
5587                               12.8                            NaN
6456                                NaN                            NaN
6460                                NaN                            NaN
6776                                NaN                            NaN
6959                                NaN                            NaN
7297                               11.7                            NaN
7351                               12.8                            NaN
8481                                4.2                            NaN
8483                               10.4                            NaN
8484                               11.8                            NaN
8564                                NaN                            NaN
9004                                8.7                            NaN
9006                               12.7                            NaN
9394                               12.0                            NaN
9569                                9.6                            NaN
10644                               NaN                            NaN
10648                              11.0                            NaN
10652                              12.7                            NaN
11476                               9.2                            NaN
11528                               8.5                            NaN
11662                               NaN                            NaN
11782                              11.9                            NaN
12255                               9.2                            NaN
12265                               7.3                            NaN
12267                               9.6                            NaN

       Basal Injection Units  Insulin Injection Units (pump)  Insulin (Meal)  \
187                      NaN                             NaN             NaN
422                      NaN                             NaN             NaN
544                      NaN                             NaN             NaN
757                      NaN                             NaN             NaN
760                      NaN                             NaN             2.5
829                      NaN                             NaN             NaN
1332                     NaN                             NaN             0.5
1434                     NaN                             NaN             NaN
1522                     NaN                             NaN             NaN
1808                     NaN                             NaN             3.0
1816                     NaN                             NaN             NaN
1843                     NaN                             NaN             NaN
1951                     NaN                             NaN             NaN
2407                     NaN                             NaN             NaN
2413                     NaN                             NaN             NaN
2707                     NaN                             NaN             3.0
2768                     NaN                             NaN             NaN
2823                     NaN                             NaN             NaN
2837                     NaN                             NaN             NaN
2839                     NaN                             NaN             NaN
2873                     NaN                             NaN             NaN
3061                     NaN                             NaN             NaN
3083                     NaN                             NaN             4.5
3600                     NaN                             NaN             NaN
4269                     NaN                             NaN             NaN
4676                     NaN                             NaN             NaN
4751                     NaN                             NaN             NaN
5010                     NaN                             NaN             7.0
5186                     NaN                             NaN             NaN
5206                     NaN                             NaN             NaN
5587                     NaN                             NaN             NaN
6456                     NaN                             NaN             NaN
6460                     NaN                             NaN             NaN
6776                     NaN                             NaN             NaN
6959                     NaN                             NaN             NaN
7297                     NaN                             NaN             NaN
7351                     NaN                             NaN             NaN
8481                     NaN                             NaN             NaN
8483                     NaN                             NaN             NaN
8484                     NaN                             NaN             NaN
8564                     NaN                             NaN             NaN
9004                     NaN                             NaN             NaN
9006                     NaN                             NaN             NaN
9394                     NaN                             NaN             NaN
9569                     NaN                             NaN             NaN
10644                    NaN                             NaN             NaN
10648                    NaN                             NaN             8.0
10652                    NaN                             NaN             NaN
11476                    NaN                             NaN             NaN
11528                    NaN                             NaN             NaN
11662                    NaN                             NaN             NaN
11782                    NaN                             NaN             NaN
12255                    NaN                             NaN             NaN
12265                    NaN                             NaN             NaN
12267                    NaN                             NaN             NaN

       Insulin (Correction)  Temporary Basal Percentage  ...  Location  \
187                     1.0                         NaN  ...       NaN
422                     NaN                         NaN  ...       NaN
544                     1.5                         NaN  ...       NaN
757                     NaN                         NaN  ...       NaN
760                     3.5                         NaN  ...       NaN
829                     NaN                         NaN  ...       NaN
1332                    NaN                         NaN  ...       NaN
1434                    NaN                         NaN  ...       NaN
1522                    0.5                         NaN  ...       NaN
1808                    2.5                         NaN  ...       NaN
1816                    1.5                         NaN  ...       NaN
1843                    NaN                         NaN  ...       NaN
1951                    NaN                         NaN  ...       NaN
2407                    1.5                         NaN  ...       NaN
2413                    NaN                         NaN  ...       NaN
2707                    2.5                         NaN  ...       NaN
2768                    2.0                         NaN  ...       NaN
2823                    3.0                         NaN  ...       NaN
2837                    1.5                         NaN  ...       NaN
2839                    0.5                         NaN  ...       NaN
2873                    NaN                         NaN  ...       NaN
3061                    NaN                         NaN  ...       NaN
3083                    3.0                         NaN  ...       NaN
3600                    NaN                         NaN  ...       NaN
4269                    NaN                         NaN  ...       NaN
4676                    NaN                         NaN  ...       NaN
4751                    NaN                         NaN  ...       NaN
5010                    NaN                         NaN  ...       NaN
5186                    NaN                         NaN  ...       NaN
5206                    NaN                         NaN  ...       NaN
5587                    NaN                         NaN  ...       NaN
6456                    NaN                         NaN  ...       NaN
6460                    NaN                         NaN  ...       NaN
6776                    NaN                         NaN  ...       NaN
6959                    NaN                         NaN  ...       NaN
7297                    NaN                         NaN  ...       NaN
7351                    NaN                         NaN  ...       NaN
8481                    NaN                         NaN  ...       NaN
8483                    NaN                         NaN  ...       NaN
8484                    1.0                         NaN  ...       NaN
8564                    NaN                         NaN  ...       NaN
9004                    NaN                         NaN  ...       NaN
9006                    NaN                         NaN  ...       NaN
9394                    NaN                         NaN  ...       NaN
9569                    NaN                         NaN  ...       NaN
10644                   NaN                         NaN  ...       NaN
10648                   NaN                         NaN  ...       NaN
10652                   1.0                         NaN  ...       NaN
11476                   NaN                         NaN  ...       NaN
11528                   NaN                         NaN  ...       NaN
11662                   NaN                         NaN  ...       NaN
11782                   NaN                         NaN  ...       NaN
12255                   NaN                         NaN  ...       NaN
12265                   NaN                         NaN  ...       NaN
12267                   NaN                         NaN  ...       NaN

       Blood pressure Body weight (kg)  HbA1c (mmol/mol)  Ketones Food type  \
187               NaN              NaN               NaN      0.0       NaN
422               NaN              NaN               NaN      0.0       NaN
544               NaN              NaN               NaN      0.0       NaN
757               NaN              NaN               NaN      0.2       NaN
760               NaN              NaN               NaN      0.6       NaN
829               NaN              NaN               NaN      0.2       NaN
1332              NaN              NaN               NaN      0.3       NaN
1434              NaN              NaN               NaN      0.0       NaN
1522              NaN              NaN               NaN      0.0       NaN
1808              NaN              NaN               NaN      0.0       NaN
1816              NaN              NaN               NaN      0.0       NaN
1843              NaN              NaN               NaN      0.2       NaN
1951              NaN              NaN               NaN      0.1       NaN
2407              NaN              NaN               NaN      0.1       NaN
2413              NaN              NaN               NaN      0.1       NaN
2707              NaN              NaN               NaN      0.1       NaN
2768              NaN              NaN               NaN      0.4       NaN
2823              NaN              NaN               NaN      0.1       NaN
2837              NaN              NaN               NaN      0.1       NaN
2839              NaN              NaN               NaN      0.1       NaN
2873              NaN              NaN               NaN      0.0       NaN
3061              NaN              NaN               NaN      0.0       NaN
3083              NaN              NaN               NaN      0.1       NaN
3600              NaN              NaN               NaN      0.4       NaN
4269              NaN              NaN               NaN      0.2       NaN
4676              NaN              NaN               NaN      0.1       NaN
4751              NaN              NaN               NaN      0.1       NaN
5010              NaN              NaN               NaN      0.1       NaN
5186              NaN              NaN               NaN      0.1       NaN
5206              NaN              NaN               NaN      0.3       NaN
5587              NaN              NaN               NaN      0.1       NaN
6456              NaN              NaN               NaN      0.1       NaN
6460              NaN              NaN               NaN      0.1       NaN
6776              NaN              NaN               NaN      0.0       NaN
6959              NaN              NaN               NaN      0.3       NaN
7297              NaN              NaN               NaN      0.2       NaN
7351              NaN              NaN               NaN      0.3       NaN

# Initial observations for Data Cleaning:
# Remove rows
1. Basal Injection Units: night time Lantus (long-acting insulin) injections display in a different format to meal and blood test data, so should be isolated for separate analysis (e.g. row 8, Basal Injection Units = 10)
2. Ketones: these are entries following ketone tests and should also be isolated for separate analysis

# Remove columns
3. Null Data Columns: Multiple columns have 0 non-null values (no data) - these should be removed
4. Low Data Entry Columns: a number columns have very few entries so we should also exclude these for simplicity i.e. Meal Descriptions, Activity Duration (Minutes), Activity Description

# Change date format
5. Date and Time: these are being read as objects - need to parse as date/time
6. Order: Data is ordered by date descending (i.e. latest data first)- it may be useful to reorder it

# Re-organise tag information
7. Tags: these are in a comma-separated string which is unusable - need to restructure into multiple columns or tag their presence in columns with 1 vs 0

## 1. Basal Injection Units: Remove rows (not null)
Night time Lantus (long-acting insulin) injections display in a different format to meal and blood test data, so should be isolated for separate analysis (e.g. row 8, Basal Injection Units = 10)

In [ ]:
# Column 'Basal Injection Units' is not null when a row refers to a lantus injection - remove these
df = df[df['Basal Injection Units'].isnull()]
df.describe() # Check there are no rows with data for 'Basal Injection Units'

,Blood Sugar Measurement (mmol/L),Insulin Injection Units (Pen),Basal Injection Units,Insulin Injection Units (pump),Insulin (Meal),Insulin (Correction),Temporary Basal Percentage,Temporary Basal Duration (Minutes),"Meal Carbohydrates (Grams, Factor 1)",Activity Duration (Minutes),...,Steps,Location,Blood pressure,Body weight (kg),HbA1c (mmol/mol),Ketones,Food type,Medication,Latitude,Longitude
count,11987.000000,0.0,0.0,0.0,4013.000000,769.000000,0.0,0.0,5828.000000,13.000000,...,0.0,0.0,0.0,0.0,0.0,55.000000,0.0,0.0,0.0,0.0
mean,6.242204,NaN,NaN,NaN,4.075903,0.982445,NaN,NaN,35.339739,58.846154,...,NaN,NaN,NaN,NaN,NaN,0.149091,NaN,NaN,NaN,NaN
std,2.062566,NaN,NaN,NaN,2.508929,0.799180,NaN,NaN,22.482048,74.976492,...,NaN,NaN,NaN,NaN,NaN,0.176250,NaN,NaN,NaN,NaN
min,1.700000,NaN,NaN,NaN,0.500000,0.500000,NaN,NaN,2.000000,15.000000,...,NaN,NaN,NaN,NaN,NaN,0.000000,NaN,NaN,NaN,NaN
25%,4.700000,NaN,NaN,NaN,3.000000,0.500000,NaN,NaN,12.000000,20.000000,...,NaN,NaN,NaN,NaN,NaN,0.000000,NaN,NaN,NaN,NaN
50%,5.900000,NaN,NaN,NaN,4.000000,1.000000,NaN,NaN,34.000000,40.000000,...,NaN,NaN,NaN,NaN,NaN,0.100000,NaN,NaN,NaN,NaN
75%,7.500000,NaN,NaN,NaN,5.500000,1.000000,NaN,NaN,50.000000,60.000000,...,NaN,NaN,NaN,NaN,NaN,0.200000,NaN,NaN,NaN,NaN
max,21.000000,NaN,NaN,NaN,72.000000,12.000000,NaN,NaN,166.000000,300.000000,...,NaN,NaN,NaN,NaN,NaN,0.600000,NaN,NaN,NaN,NaN

## 2. Ketones: Remove rows (not null)
 These are row entries following ketone tests and should also be isolated for separate analysis

In [ ]:
# Column 'Ketones' holds data for ketone tests and should also be removed
df = df[df['Ketones'].isnull()]
df.describe() # Check there are no rows with data for 'Ketones'

,Blood Sugar Measurement (mmol/L),Insulin Injection Units (Pen),Basal Injection Units,Insulin Injection Units (pump),Insulin (Meal),Insulin (Correction),Temporary Basal Percentage,Temporary Basal Duration (Minutes),"Meal Carbohydrates (Grams, Factor 1)",Activity Duration (Minutes),...,Steps,Location,Blood pressure,Body weight (kg),HbA1c (mmol/mol),Ketones,Food type,Medication,Latitude,Longitude
count,11951.000000,0.0,0.0,0.0,4006.000000,754.000000,0.0,0.0,5823.000000,13.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
mean,6.224500,NaN,NaN,NaN,4.075911,0.966844,NaN,NaN,35.346213,58.846154,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,2.033436,NaN,NaN,NaN,2.509046,0.788927,NaN,NaN,22.489556,74.976492,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,1.700000,NaN,NaN,NaN,0.500000,0.500000,NaN,NaN,2.000000,15.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,4.700000,NaN,NaN,NaN,3.000000,0.500000,NaN,NaN,12.000000,20.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,5.900000,NaN,NaN,NaN,4.000000,1.000000,NaN,NaN,34.000000,40.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,7.400000,NaN,NaN,NaN,5.500000,1.000000,NaN,NaN,50.000000,60.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,21.000000,NaN,NaN,NaN,72.000000,12.000000,NaN,NaN,166.000000,300.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## 3. and 4. Remove null and low data columns

In [ ]:
# Multiple columns have 0 non-null values (no data) - these should be removed
# Many columns have very low amounts of data (e.g. 12 rows) - these should also be removed
# New, useful data set with reduced columns
df = df[['Date',
             'Time',
             'Tags',
             'Blood Sugar Measurement (mmol/L)',
             'Insulin (Meal)',
             'Insulin (Correction)',
             'Meal Carbohydrates (Grams, Factor 1)']]

df.head()

,Date,Time,Tags,Blood Sugar Measurement (mmol/L),Insulin (Meal),Insulin (Correction),"Meal Carbohydrates (Grams, Factor 1)"
0,24 Jul 2025,13:21:14,"Lunch,Before meal",4.6,3.0,NaN,54.0
1,24 Jul 2025,13:18:46,"Before meal,Breakfast",5.7,2.0,NaN,22.0
2,23 Jul 2025,20:07:44,"Before meal,Dinner",7.6,3.0,0.5,54.0
3,23 Jul 2025,16:45:09,"Office work,Snack,After meal",4.6,1.5,NaN,28.0
4,23 Jul 2025,16:32:35,"Office work,After meal",4.5,NaN,NaN,NaN

## 5. Clean Date and Time columns to read as date/time variables

In [ ]:
# 1. Date and Time: these are being read as objects - we need to parse these columns as date/time

# Problem 1: 'Date' is currently in the format '%d %b %Y' (e.g. 10 Jun 2025)
# Problem 2: "30 Sept 2024" fails because "Sept" is not a standard abbreviation for September that pandas recognizes with %b.
# The standard abbreviation is typically "Sep", so we must find the instances of 'Sept' in the 'Date' column and replace them with 'Sep'

# Solution: From 'Date' (currently a string), extract 'Day' (first 1-2 characters), 'Year' (last 4 characters) and Month (middle 3-4 characters

# Year - this is the easiest. Take the last 4 characters of the string 'Date'
df['Year'] = df['Date'].str[-4:]
df['Year'].value_counts() # confirms the dates 2021-2025 have been successfully extracted

Year
2023    4744
2024    4226
2021    2365
2025    1927
2022    1189
Name: count, dtype: int64

In [ ]:
# Day - using the .str.partition() method, the day is partitioned from the month and year (which have remained grouped as a string because of the inconsistent formatting)
day = df['Date'].str.partition(' ')[0]

# Check values lie between 1 and 31 - they do! (Note: the data is currently an array)
day.unique()

# Convert the array to a series so it can be appended to the original dataframe
df['Day'] = pd.Series(day)
df.head(10)

,Date,Time,Tags,Blood Sugar Measurement (mmol/L),Insulin (Meal),Insulin (Correction),"Meal Carbohydrates (Grams, Factor 1)",Year,Day
0,24 Jul 2025,13:21:14,"Lunch,Before meal",4.6,3.0,NaN,54.0,2025,24
1,24 Jul 2025,13:18:46,"Before meal,Breakfast",5.7,2.0,NaN,22.0,2025,24
2,23 Jul 2025,20:07:44,"Before meal,Dinner",7.6,3.0,0.5,54.0,2025,23
3,23 Jul 2025,16:45:09,"Office work,Snack,After meal",4.6,1.5,NaN,28.0,2025,23
4,23 Jul 2025,16:32:35,"Office work,After meal",4.5,NaN,NaN,NaN,2025,23
5,23 Jul 2025,13:17:25,"Lunch,Before meal",6.2,2.0,NaN,33.0,2025,23
6,23 Jul 2025,10:02:16,"Before meal,Breakfast",4.8,2.5,NaN,34.0,2025,23
7,23 Jul 2025,9:34:00,NaN,5.4,NaN,NaN,NaN,2025,23
9,22 Jul 2025,19:52:55,"Before meal,Dinner",4.6,6.5,NaN,113.0,2025,22
10,22 Jul 2025,13:24:29,"Lunch,Before meal",4.5,1.5,NaN,33.0,2025,22

In [ ]:
# Month - this can be extracted from the second part of the partition, referencing the text that comes before the space (which we know is at index -5)
month_year = df['Date'].str.partition(' ')[2]
month = month_year.str[:-5]
# Check for just the 12 months
month.unique()

array(['Jul', 'Jun', 'May', 'Apr', 'Mar', 'Feb', 'Jan', 'Dec', 'Nov',
       'Oct', 'Sept', 'Aug'], dtype=object)

In [ ]:
# Change the instances of 'Sept' to 'Sep'
# Convert the array to a series so it can be appended to the original dataframe
df['Month'] = pd.Series(month)
df.loc[df.Month == 'Sept', 'Month'] = "Sep"

# Check if all Septembers are 'Sep'
df['Month'].unique()

array(['Jul', 'Jun', 'May', 'Apr', 'Mar', 'Feb', 'Jan', 'Dec', 'Nov',
       'Oct', 'Sep', 'Aug'], dtype=object)

In [ ]:
# Create new 'Date_New' variable from our new 'Day', 'Month' and 'Year' columns by concatenating these string variables
df['Date_Str'] = df['Day'] + ' ' + df['Month'] + ' ' + df['Year']
df.head()

# Convert to the standard pandas format of '%Y-%m-%d' using .to_datetime()
df['Date_New'] = pd.to_datetime(df['Date_Str'], format='%d %b %Y')
# df['date'] = pd.to_datetime(dict(year=df['Year'], month=df['Month_Number'], day=df['Day']))

df.sample(20)
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 14451 entries, 0 to 15642
Data columns (total 12 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   Date                                  14451 non-null  object
 1   Time                                  14451 non-null  object
 2   Tags                                  11233 non-null  object
 3   Blood Sugar Measurement (mmol/L)      11951 non-null  float64
 4   Insulin (Meal)                        4006 non-null   float64
 5   Insulin (Correction)                  754 non-null    float64
 6   Meal Carbohydrates (Grams, Factor 1)  5823 non-null   float64
 7   Year                                  14451 non-null  object
 8   Day                                   14451 non-null  object
 9   Month                                 14451 non-null  object
 10  Date_Str                              14451 non-null  object
 11  Date_New                              14451 non-null  datetime64[ns]
dtypes: datetime64[ns](1), float64(4), object(7)
memory usage: 1.9+ MB

In [ ]:
# Convert 'Time' to a date/time variable, using just the time format
df['Time_New'] = pd.to_datetime(df['Time'], format='%H:%M:%S').dt.strftime('%H:%M:%S')

df['Date_Time'] = pd.to_datetime(df['Date_New'].astype(str) + ' ' + df['Time_New'].astype(str))
df.info()
df.head(10)

<class 'pandas.core.frame.DataFrame'>
Index: 14451 entries, 0 to 15642
Data columns (total 14 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   Date                                  14451 non-null  object
 1   Time                                  14451 non-null  object
 2   Tags                                  11233 non-null  object
 3   Blood Sugar Measurement (mmol/L)      11951 non-null  float64
 4   Insulin (Meal)                        4006 non-null   float64
 5   Insulin (Correction)                  754 non-null    float64
 6   Meal Carbohydrates (Grams, Factor 1)  5823 non-null   float64
 7   Year                                  14451 non-null  object
 8   Day                                   14451 non-null  object
 9   Month                                 14451 non-null  object
 10  Date_Str                              14451 non-null  object
 11  Date_New                              14451 non-null  datetime64[ns]
 12  Time_New                              14451 non-null  object
 13  Date_Time                             14451 non-null  datetime64[ns]
dtypes: datetime64[ns](2), float64(4), object(8)
memory usage: 2.2+ MB

,Date,Time,Tags,Blood Sugar Measurement (mmol/L),Insulin (Meal),Insulin (Correction),"Meal Carbohydrates (Grams, Factor 1)",Year,Day,Month,Date_Str,Date_New,Time_New,Date_Time
0,24 Jul 2025,13:21:14,"Lunch,Before meal",4.6,3.0,NaN,54.0,2025,24,Jul,24 Jul 2025,2025-07-24,13:21:14,2025-07-24 13:21:14
1,24 Jul 2025,13:18:46,"Before meal,Breakfast",5.7,2.0,NaN,22.0,2025,24,Jul,24 Jul 2025,2025-07-24,13:18:46,2025-07-24 13:18:46
2,23 Jul 2025,20:07:44,"Before meal,Dinner",7.6,3.0,0.5,54.0,2025,23,Jul,23 Jul 2025,2025-07-23,20:07:44,2025-07-23 20:07:44
3,23 Jul 2025,16:45:09,"Office work,Snack,After meal",4.6,1.5,NaN,28.0,2025,23,Jul,23 Jul 2025,2025-07-23,16:45:09,2025-07-23 16:45:09
4,23 Jul 2025,16:32:35,"Office work,After meal",4.5,NaN,NaN,NaN,2025,23,Jul,23 Jul 2025,2025-07-23,16:32:35,2025-07-23 16:32:35
5,23 Jul 2025,13:17:25,"Lunch,Before meal",6.2,2.0,NaN,33.0,2025,23,Jul,23 Jul 2025,2025-07-23,13:17:25,2025-07-23 13:17:25
6,23 Jul 2025,10:02:16,"Before meal,Breakfast",4.8,2.5,NaN,34.0,2025,23,Jul,23 Jul 2025,2025-07-23,10:02:16,2025-07-23 10:02:16
7,23 Jul 2025,9:34:00,NaN,5.4,NaN,NaN,NaN,2025,23,Jul,23 Jul 2025,2025-07-23,09:34:00,2025-07-23 09:34:00
9,22 Jul 2025,19:52:55,"Before meal,Dinner",4.6,6.5,NaN,113.0,2025,22,Jul,22 Jul 2025,2025-07-22,19:52:55,2025-07-22 19:52:55
10,22 Jul 2025,13:24:29,"Lunch,Before meal",4.5,1.5,NaN,33.0,2025,22,Jul,22 Jul 2025,2025-07-22,13:24:29,2025-07-22 13:24:29

In [ ]:
df_final = df[['Date_New',
              'Date_Time',
              'Month',
              'Year',
              'Blood Sugar Measurement (mmol/L)',
              'Insulin (Meal)',
              'Insulin (Correction)',
              'Meal Carbohydrates (Grams, Factor 1)',
              'Tags']]

df_final.head()

,Date_New,Date_Time,Month,Year,Blood Sugar Measurement (mmol/L),Insulin (Meal),Insulin (Correction),"Meal Carbohydrates (Grams, Factor 1)",Tags
0,2025-07-24,2025-07-24 13:21:14,Jul,2025,4.6,3.0,NaN,54.0,"Lunch,Before meal"
1,2025-07-24,2025-07-24 13:18:46,Jul,2025,5.7,2.0,NaN,22.0,"Before meal,Breakfast"
2,2025-07-23,2025-07-23 20:07:44,Jul,2025,7.6,3.0,0.5,54.0,"Before meal,Dinner"
3,2025-07-23,2025-07-23 16:45:09,Jul,2025,4.6,1.5,NaN,28.0,"Office work,Snack,After meal"
4,2025-07-23,2025-07-23 16:32:35,Jul,2025,4.5,NaN,NaN,NaN,"Office work,After meal"

In [ ]:
df_final = df_final.rename(columns={'Date_New': 'Date',
                              'Blood Sugar Measurement (mmol/L)': 'Blood Sugar',
                              'Meal Carbohydrates (Grams, Factor 1)': 'Carbohydrates (g)'})
df_final.info()

<class 'pandas.core.frame.DataFrame'>
Index: 14451 entries, 0 to 15642
Data columns (total 9 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Date                  14451 non-null  datetime64[ns]
 1   Date_Time             14451 non-null  datetime64[ns]
 2   Month                 14451 non-null  object
 3   Year                  14451 non-null  object
 4   Blood Sugar           11951 non-null  float64
 5   Insulin (Meal)        4006 non-null   float64
 6   Insulin (Correction)  754 non-null    float64
 7   Carbohydrates (g)     5823 non-null   float64
 8   Tags                  11233 non-null  object
dtypes: datetime64[ns](2), float64(4), object(3)
memory usage: 1.6+ MB

# Re-organise tag information
7. Tags: these are in a comma-separated string which is unusable - need to restructure into multiple columns or tag their presence in columns with 1 vs 0

Unfortunatly, the combinations of tags are considered as unique strings. I have to find a way to separate them

In [ ]:
# Find the unique instances of 'Tags'
df['Tags'].unique()

array(['Lunch,Before meal', 'Before meal,Breakfast', 'Before meal,Dinner',
       'Office work,Snack,After meal', 'Office work,After meal', nan,
       'Stress,Office work,After meal',
       'Hyperglycemia feeling,After meal', 'After meal',
       'Snack,After meal', 'Bedtime', 'Hypoglycemia feeling,After meal',
       'Hypoglycemia feeling', 'Lunch,Before meal,Carb guess',
       'Lunch,Eating out,Before meal,Carb guess', 'After meal,Bedtime',
       'Before meal,Carb guess,Dinner', 'Foot on the floor',
       'Hypoglycemia feeling,Lunch,Eating out,Tired,Before meal,Carb guess',
       'Hypoglycemia feeling,After meal,Dinner',
       'Hypoglycemia feeling,Snack,Before meal,After meal',
       'Driving,Hypoglycemia feeling,On the way,After meal',
       'Office work,Tired,After meal',
       'Eating out,Lunch,Before meal,Carb guess',
       'Hypoglycemia feeling,Office work,After meal',
       'Hypoglycemia feeling,Before meal,Dinner',
       'Lunch,Tired,Before meal', 'Office work,Snack,Tired,After meal',
       'Hyperglycemia feeling,Tired,After meal',
       'Driving,Before meal,On the way,Carb guess,Dinner',
       'Snack,Before meal', 'Tired,After meal',
       'Snack,After meal,Breakfast', 'Snack',
       'Foot on the floor,Before meal',
       'Hypoglycemia feeling,Snack,After meal',
       'Manual work,Before meal,Carb guess,Headache,Dinner',
       'Manual work,After meal',
       'Hypoglycemia feeling,Foot on the floor,Tired',
       'Special situation,Before meal,Carb guess,Dinner',
       'Snack,Before meal,After meal',
       'Hyperglycemia feeling,Stress,Office work,After meal', 'At night',
       'Travelling,After meal', 'Before meal,Vacation,Breakfast',
       'Foot on the floor,Vacation',
       'Eating out,Before meal,Vacation,Carb guess,Dinner',
       'Lunch,Before meal,Vacation', 'Snack,Vacation',
       'Vacation,After meal', 'Vacation,After meal,Bedtime',
       'Hypoglycemia feeling,Vacation,After meal',
       'Eating out,Vacation,Before meal,Carb guess,Dinner',
       'Snack,Vacation,After meal', 'Tired,Vacation,After meal,Bedtime',
       'Lunch,Vacation,Before meal', 'Vacation,Before meal,Breakfast',
       'Eating out,Tired,Before meal,Vacation,Carb guess,Dinner',
       'Hypoglycemia feeling,Snack,Vacation,After meal',
       'Eating out,Snack,Vacation,Carb guess,After meal',
       'Hyperglycemia feeling,Eating out,Before meal,Vacation,Carb guess,Dinner',
       'Breakfast', 'Hyperglycemia feeling,Office work,Tired,After meal',
       'Hyperglycemia feeling,Lunch,Before meal,Carb guess',
       'Hypoglycemia feeling,Lunch,Before meal',
       'Hypoglycemia feeling,After meal,Housework',
       'Hypoglycemia feeling,Manual work',
       'Hyperglycemia feeling,Office work,After meal',
       'Driving,After meal', 'Eating out,Lunch,Before meal',
       'Snack,Tired,Before meal',
       'Hypoglycemia feeling,Office work,Snack,After meal',
       'Snack,Bedtime', 'Office work,Nervous,After meal',
       'Travelling,Excited,Nervous,On the way,After meal',
       'Travelling,Lunch,Nervous,On the way,Before meal',
       'Driving,Snack,After meal', 'Hypoglycemia feeling,Snack',
       'Eating out,Special situation,Before meal,Carb guess,Dinner',
       'Nervous,Tired,Carb guess,After meal',
       'Hypoglycemia feeling,Office work,Nervous,After meal,Headache',
       'Office work,Tired,After meal,Headache',
       'Office work,After meal,Headache',
       'Hyperglycemia feeling,Office work,Before meal',
       'Hyperglycemia feeling,Stress,Office work,Angry,After meal',
       'Hyperglycemia feeling,Office work,Sad,After meal',
       'After sports,After meal',
       'Eating out,Lunch,Special situation,Before meal,Carb guess',
       'Office work,Before meal',
       'Driving,Eating out,Lunch,On the way,Before meal',
       'Driving,Hypoglycemia feeling', 'Before meal,Carb guess',
       'Before meal', 'Snack,After meal,Bedtime',
       'Hypoglycemia feeling,Angry,After meal',
       'Hyperglycemia feeling,Office work,Angry,Tired,After meal,Sick',
       'Hyperglycemia feeling,Office work,Tired,After meal,Sick',
       'Hypoglycemia feeling,Office work,Tired,After meal,Sick',
       'Office work,Tired,After meal,Sick',
       'Eating out,Before meal,Carb guess,Dinner',
       'Eating out,Lunch,Before meal,Carb guess,Sick',
       'Driving,Tired,After meal,Sick',
       'Driving,Snack,Tired,After meal,Sick', 'Tired,After meal,Sick',
       'Tired,Before meal,Sick', 'Snack,Tired,After meal,Sick', 'Sick',
       'Before meal,Sick,Dinner', 'After meal,Sick',
       'Lunch,Tired,Before meal,Sick', 'Foot on the floor,Tired',
       'Tired,Before meal,Dinner', 'Tired',
       'Special situation,Carb guess', 'Driving,Snack',
       'Office work,Snack', 'Office work,Before meal,Dinner',
       'Lunch,Hypoglycemia feeling,Office work,After meal',
       'Hypoglycemia feeling,Tired,After meal',
       'Hypoglycemia feeling,Snack,Tired,After meal', 'Driving',
       'After meal,Sick,Bedtime', 'Snack,Sick',
       'Tired,Before meal,Carb guess,Dinner',
       'Hypoglycemia feeling,Office work,Tired,After meal',
       'After meal,Dinner', 'Pain,Before meal,Headache,Dinner',
       'Lunch,Eating out,Hypoglycemia feeling,Before meal,Carb guess',
       'Hypoglycemia feeling,Before meal',
       'Hypoglycemia feeling,Snack,After meal,Carb guess',
       'Hyperglycemia feeling,Lunch,Before meal', 'Stress,After meal',
       'Lunch,Before meal,Breakfast',
       'Eating out,Before meal,Carb guess,Breakfast',
       'Travelling,Tired,After meal', 'Snack,Carb guess',
       'Lunch,Eating out,Tired,Before meal,Carb guess,Breakfast',
       'Hyperglycemia feeling,Tired,Before meal',
       'Lunch,Hypoglycemia feeling,Before meal',
       'Tired,Before meal,Headache,Dinner', 'Tired,After meal,Headache',
       'Stress,Tired,After meal,Headache',
       'Travelling,Before meal,On the way,Breakfast',
       'Lunch,Nervous,Before meal',
       'Office work,Snack,Tired,After meal,Headache',
       'Hyperglycemia feeling,Office work,Tired,After meal,Headache',
       'Office work,Snack,Sad,After meal', 'Office work,Sad,After meal',
       'Hyperglycemia feeling,After meal,Bedtime',
       'Stress,Before meal,Breakfast', 'Snack,After meal,Dinner',
       'Stress,Office work,Snack,Sad,After meal',
       'Snack,Special situation,After meal,Carb guess,Party', 'Dinner',
       'Hyperglycemia feeling,Stress,Office work,Tired,After meal',
       'Hyperglycemia feeling', 'Hyperglycemia feeling,Office work',
       'Office work,Snack,Before meal', 'Stress,Angry,After meal',
       'Lunch,Hypoglycemia feeling,Tired,Before meal',
       'Hypoglycemia feeling,Tired,Before meal',
       'Snack,Tired,Carb guess,After meal', 'Stress,Before meal',
       'Eating out,Before meal,Dinner', 'Lunch',
       'Tired,Before meal,Breakfast', 'Office work,Sad,Tired,After meal',
       'Hyperglycemia feeling,Hypoglycemia feeling,Office work,Tired,After meal',
       'Office work,Before meal,Breakfast',
       'Hyperglycemia feeling,Hypoglycemia feeling,Office work,After meal',
       'Hypoglycemia feeling,Bedtime', 'Special situation,After meal',
       'Driving,Lunch,Before meal',
       'Hyperglycemia feeling,Office work,Snack,After meal',
       'Eating out,Special situation,Before meal,Carb guess,Breakfast,Dinner',
       'Hyperglycemia feeling,Tired,Before meal,Breakfast',
       'Before meal,Carb guess,Breakfast',
       'Hyperglycemia feeling,Tired,After meal,Sick',
       'Hyperglycemia feeling,Special situation,After meal',
       'Hyperglycemia feeling,Eating out,Special situation,Carb guess,Dinner',
       'Eating out,Special situation,Carb guess,Dinner',
       'On the way,Before meal,Carb guess,Dinner',
       'Office work,After meal,Headache,Sick', 'Lunch,Before meal,Sick',
       'Office work,Snack,After meal,Sick',
       'Hypoglycemia feeling,Office work,Before meal,Sick',
       'Hyperglycemia feeling,Office work,Tired,Before meal',
       'Hypoglycemia feeling,Snack,Tired', 'Eating out,Carb guess,Dinner',
       'Snack,Before meal,Bedtime',
       'Eating out,Snack,Special situation,After meal',
       'Lunch,Eating out,Special situation,Before meal',
       'Special situation,On the way,After meal',
       'Travelling,Hypoglycemia feeling,On the way,After meal',
       'Travelling,Before meal,Dinner',
       'Travelling,Before meal,Breakfast', 'Vacation',
       'Eating out,Before meal,Vacation,Carb guess,After meal,Dinner',
       'Lunch,Tired,Vacation,Before meal',
       'Vacation,Before meal,Carb guess,Dinner',
       'Happy,Special situation,Before meal,Breakfast',
       'Hyperglycemia feeling,Before meal,Breakfast',
       'Special situation,Before meal,Dinner',
       'Hypoglycemia feeling,Tired',
       'Office work,Special situation,After meal',
       'Before meal,Fasting,Breakfast', 'Hyperglycemia feeling,At night',
       'Hyperglycemia feeling,After meal,At night',
       'Foot on the floor,Tired,After meal',
       'Lunch,Special situation,Before meal',
       'Travelling,Special situation,On the way,After meal',
       'Tired,Before meal,Fasting,Breakfast', 'Before meal,Fasting',
       'Hyperglycemia feeling,Stress,Nervous,Tired,After meal',
       'Stress,Lunch,Nervous,Tired,Before meal',
       'Hyperglycemia feeling,Stress,Office work,Nervous,Tired,After meal',
       'Stress,Office work,Nervous,After meal',
       'Hyperglycemia feeling,Stress,Nervous,Tired,Before meal,Fasting,Breakfast',
       'Stress,Nervous,After meal,Sick,At night', 'Nervous,After meal',
       'Hyperglycemia feeling,Before meal,Fasting',
       'Hyperglycemia feeling,Office work,Nervous,Tired,After meal',
       'Lunch,Nervous,Tired,Before meal',
       'Hyperglycemia feeling,Lunch,Nervous,Before meal',
       'Hyperglycemia feeling,Nervous,Before meal,Fasting,Breakfast',
       'After meal,Headache,Sick,Bedtime',
       'Lunch,Special situation,Before meal,Carb guess',
       'Travelling,Lunch,Before meal',
       'Eating out,Vacation,Before meal,Carb guess,Headache,Dinner',
       'Stress,Tired,Before meal,Fasting,Breakfast',
       'Stress,Nervous,Tired,At night', 'Lunch,Manual work,Before meal',
       'Hypoglycemia feeling,Snack,Manual work',
       'Hypoglycemia feeling,Manual work,After meal',
       'Special situation,Before meal,Fasting',
       'Hyperglycemia feeling,Office work,After meal,Sick',
       'Office work,After meal,Sick',
       'Hypoglycemia feeling,Office work,After meal,Sick',
       'Before meal,Fasting,Sick', 'Lunch,Office work,Before meal,Sick',
       'Tired,Before meal,Headache,Sick', 'After meal,Headache,Sick',
       'Foot on the floor,After meal,Sick', 'Sick,Bedtime',
       'Hypoglycemia feeling,Before meal,Sick',
       'Before meal,Fasting,Sick,Headache', 'After meal,Sick,Headache',
       'Fasting,Sick', 'Eating out,Carb guess,Sick,Dinner',
       'Eating out,Before meal,Carb guess,Sick,Dinner',
       'Office work,Tired,Before meal,Sick',
       'Tired,Before meal,Fasting,Sick',
       'Hypoglycemia feeling,Tired,After meal,Sick',
       'Carb guess,Breakfast', 'After meal,Housework',
       'Driving,Before meal,Fasting',
       'Foot on the floor,Before meal,Fasting', 'Eating out,Carb guess',
       'Tired,Before meal', 'Foot on the floor,Fasting',
       'Hyperglycemia feeling,Foot on the floor,Before meal,Fasting',
       'Tired,Before meal,Fasting',
       'Hypoglycemia feeling,After meal,Bedtime',
       'Office work,Tired,Before meal',
       'Foot on the floor,Tired,Before meal,Fasting',
       'Hyperglycemia feeling,Tired,Before meal,Fasting',
       'Hyperglycemia feeling,After meal,Headache', 'Before meal,Bedtime',
       'Hyperglycemia feeling,Tired', 'Chilling,Tired,After meal',
       'After meal,At night',
       'Hypoglycemia feeling,Before meal,Housework', 'Fasting,At night',
       'Before meal,After meal', 'Carb guess,Dinner',
       'After meal,Shopping', 'Pain,Before meal,Headache', 'Snack,Tired',
       'Hypoglycemia feeling,After meal,Shopping',
       'Hypoglycemia feeling,Special situation,After meal',
       'Tired,After meal,Housework',
       'Hyperglycemia feeling,After meal,Housework',
       'Hyperglycemia feeling,Tired,After meal,Housework',
       'Eating out,Special situation,Dinner',
       'Driving,Hypoglycemia feeling,After meal', 'Fasting,After meal',
       'Before meal,Housework', 'Carb guess',
       'Hyperglycemia feeling,Hypoglycemia feeling,After meal',
       'Hyperglycemia feeling,After meal,Fasting,Housework',
       'Before meal,Sick', 'Hyperglycemia feeling,After meal,Sick',
       'Driving,Snack,Carb guess', 'Hypoglycemia feeling,Sports',
       'Lunch,Special situation,Carb guess',
       'Hyperglycemia feeling,Foot on the floor,Tired,Fasting',
       'Hyperglycemia feeling,Before meal',
       'Hypoglycemia feeling,Office work,Before meal',
       'Hyperglycemia feeling,Tired,Before meal,Sick',
       'Hypoglycemia feeling,Before meal,Fasting,Sick',
       'Hyperglycemia feeling,Before meal,Sick',
       'Hypoglycemia feeling,Office work,Snack,After meal,Sick',
       'Office work,After meal,Dinner',
       'Stress,Office work,After meal,Sick',
       'Foot on the floor,Before meal,Dinner',
       'Hypoglycemia feeling,Housework',
       'Stress,Hypoglycemia feeling,Office work,After meal',
       'Driving,Special situation,After meal', 'Fasting,Breakfast',
       'Eating out,Special situation,Carb guess,Dinner,Party',
       'Stress,Nervous', 'Lunch,Carb guess',
       'Hyperglycemia feeling,Hypoglycemia feeling,Special situation,After meal',
       'Special situation,Before meal,Breakfast',
       'Hypoglycemia feeling,Office work,Manual work,After meal',
       'Fasting', 'Chilling,After meal', 'Stress',
       'Travelling,Eating out,Before meal', 'Travelling,Snack,After meal',
       'Before meal,Vacation,Fasting',
       'Eating out,Before meal,Vacation,Carb guess',
       'Vacation,Before meal,Fasting', 'Vacation,Bedtime',
       'Eating out,Vacation,Carb guess', 'Vacation,Before meal',
       'Vacation,Breakfast', 'Vacation,Carb guess,Dinner',
       'Hypoglycemia feeling,Vacation', 'Travelling,Hypoglycemia feeling',
       'After meal,Fasting', 'Lunch,After meal',
       'Hyperglycemia feeling,Driving,After meal',
       'Pain,Office work,After meal',
       'Hyperglycemia feeling,Office work,Angry,Tired,After meal',
       'Office work,After meal,Correction', 'Driving,After meal,Shopping',
       'Hyperglycemia feeling,Office work,After meal,Correction',
       'Stress,Sad,Tired,Before meal,Dinner', 'Sad,Tired,After meal',
       'Stress,Office work,Sad,After meal', 'Sad,Before meal,Fasting',
       'Hypoglycemia feeling,After meal,Correction',
       'Foot on the floor,Sad,Before meal,Fasting', 'Sad,Bedtime',
       'Sad,Before meal', 'Office work,Sad,After meal,Correction',
       'Travelling,On the way,After meal',
       'Travelling,Hypoglycemia feeling,On the way',
       'Travelling,Before meal,On the way,Dinner',
       'Travelling,Lunch,On the way,Before meal',
       'Travelling,Snack,On the way,After meal',
       'Travelling,Sports,On the way,After meal',
       'Foot on the floor,Snack,Before meal,Vacation,Fasting',
       'Snack,Vacation,After meal,Bedtime',
       'Vacation,Before meal,Headache',
       'Travelling,On the way,Vacation,After meal',
       'Travelling,Vacation,On the way,After meal',
       'Travelling,Vacation,On the way,Before meal',
       'Eating out,Special situation,Breakfast',
       'Travelling,On the way,Vacation,Before meal,Fasting', 'Travelling',
       'Lunch,Eating out,Before meal,Fasting',
       'Hyperglycemia feeling,Driving,Correction',
       'Office work,Manual work,After meal',
       'Hyperglycemia feeling,Office work,Sad,Tired,After meal',
       'Driving,Tired,After meal', 'Foot on the floor,After meal',
       'Special situation', 'Driving,Breakfast',
       'Hypoglycemia feeling,Foot on the floor',
       'Hypoglycemia feeling,Office work',
       'Pain,Office work,Tired,After meal', 'Office work',
       'Office work,Tired',
       'Hyperglycemia feeling,Stress,Angry,Sad,Tired',
       'Lunch,Office work,Before meal', 'Before meal,Party',
       'Lunch,Special situation,Carb guess,Party',
       'Office work,Snack,Tired', 'Lunch,Office work,Tired,Before meal',
       'Lunch,Eating out,Carb guess', 'Lunch,Before meal,Headache',
       'Hyperglycemia feeling,Sick', 'Chilling,Before meal,Sick',
       'Office work,Sick', 'Sick,At night', 'Office work,Tired,Sick',
       'Hyperglycemia feeling,Office work,Sick',
       'Special situation,On the way',
       'Travelling,Special situation,On the way',
       'Stress,Angry,After meal,Housework',
       'Hypoglycemia feeling,Chilling,Before meal',
       'Pain,Foot on the floor,Before meal,Fasting',
       'Chilling,Tired,Before meal,After meal',
       'Lunch,Chilling,Before meal', 'Driving,Office work,After meal',
       'Allergies,Before meal,Fasting,Breakfast',
       'Allergies,Pain,Foot on the floor,Tired,Fasting',
       'Allergies,Bedtime', 'Correction', 'Hyperglycemia feeling,Snack',
       'Sports', 'Sports,After meal',
       'Hyperglycemia feeling,Hypoglycemia feeling',
       'Sports,Snack,After meal', 'Sports,Before meal,Dinner',
       'Snack,Before meal,Dinner', 'Lunch,Before meal,Dinner',
       'Hypoglycemia feeling,Sports,After meal', 'Sports,Snack',
       'Snack,After meal,At night',
       'Hyperglycemia feeling,Before meal,Dinner'], dtype=object)

In [ ]:
# Create new column 'Commas' and count the number of commas that appear in the column 'Tags'
df["Commas"] = df.Tags.str.count(',')
df['Commas'].head()

0    1.0
1    1.0
2    1.0
3    2.0
4    1.0
Name: Commas, dtype: float64

Option 2: Try a pandas solution (yay, it worked!)

In [ ]:
tags = df.Tags.str.split(',',expand=True).stack().unique().tolist()
print(tags)

['Lunch', 'Before meal', 'Breakfast', 'Dinner', 'Office work', 'Snack', 'After meal', 'Stress', 'Hyperglycemia feeling', 'Bedtime', 'Hypoglycemia feeling', 'Carb guess', 'Eating out', 'Foot on the floor', 'Tired', 'Driving', 'On the way', 'Manual work', 'Headache', 'Special situation', 'At night', 'Travelling', 'Vacation', 'Housework', 'Nervous', 'Excited', 'Angry', 'Sad', 'After sports', 'Sick', 'Pain', 'Party', 'Happy', 'Fasting', 'Chilling', 'Shopping', 'Sports', 'Correction', 'Allergies']

Create binary variable to indicate the presence of each tag in a column

In [ ]:
# Test out by first creating a variable 'Lunch' WRONG
if "Lunch" in df.Tags == True:
  df['Lunch'] = 1
else:
  df['Lunch'] = 0

df.head()

In [ ]:
df['Lunch1'] = (df.Tags.str.contains('Lunch').map({True : '1', False : '0'}))
df.head()